name: docker hub mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: redis
        uses: whalimeter/gh-action-image-mirror@0203b9e3b3895ef329a65d65f5b7175f20fd8e55
        with:
          image: redis
          minver: "7.2"
      - name: postgres
        uses: whalimeter/gh-action-image-mirror@0203b9e3b3895ef329a65d65f5b7175f20fd8e55
        with:
          image: postgres
          minver: "15-alpine"
